spring.application.name=AppointmentBookingSystem


# JWT secret (google -> jwt secret key generator)
app.jwt.secret=753ab8d0de7351789490fe1d3b8be9c7       


#Token expiration
app.jwt.expiration-ms=3600000